Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    public class CoverTypeController : Controller
    {
        // making the connection true the dependency injection in the controller 
        private readonly IUnitOfWork _unitOfWork;

        // making the constructor for the connection true the dependency injection in the controller

        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        // READ
        public IActionResult Index()
        {
            // calling DB information table categories
            IEnumerable<CoverType> objCoverTypeList = _unitOfWork.CoverType.GetAll();
            return View(objCoverTypeList);
        }





        // POST

        //GET
        public IActionResult Create()
        {
            return View();
        }


        //POST
        [HttpPost]
        // This is needed so that they can't hack the website true the form
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {

            // Check validations serverside => modalstate.isvalid
            if (ModelState.IsValid)
            {
                // this is a command to add something to the DB
                _unitOfWork.CoverType.Add(obj);
                // adding saveChanges it wil go to the DB and save the changes
                _unitOfWork.Save();
                TempData["success"] = "CoverType created successfully";
                // with redirectaction you can go back to the index instead of staying on the page
                // This will look for the index action inside the same controller
                // if you had to redirect to another controller, you can just do it like this example index HomeController ("index","HomeController")
                return RedirectToAction("Index");
            }
            // if you don't fill in nothing in create CoverType, it will return the view.
            return View(obj);








            // UPDATE
        }
        //GET
        // Edit will display the existing functionality of the CoverType that was selected.
        // Here we will retrieve an intiger that will be id
        public IActionResult Edit(int? id)
        {
            // Id has to exist or can not be 0
            if (id == null || id == 0)
            {
                return NotFound();
            }
            // Here we extract the id from de db with the find method. This way it tries to find the primary key based on the primary key of the table and assigned that to the variable CoverTypeFromDB.
            //var CoverType = _db.Categories.Find(id);

            // 2 other ways to retrieve an ID from CoverType

            // Here it will find the Id and it will return the first one it finds with the id you arsking for.
            var CoverTypeFromDBFirst = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
            // it returns only one element but without throwing an exeption
            // var CoverTypeFromDBSingle = _db.Categories.SingleOrDefault(u=>u.Id==id);

            // If it doesn't find a CoverType it will display not found
            if (CoverTypeFromDBFirst == null)
            {
                return NotFound();
            }
            // If it founds the CoverType it will return it to the view
            return View(CoverTypeFromDBFirst);
        }


        //POST
        [HttpPost]

        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {

          

            if (ModelState.IsValid)
            {
                // Based on the primary key the update wil automaticly update all of the properties
                _unitOfWork.CoverType.Update(obj);

                _unitOfWork.Save();
                TempData["success"] = "CoverType updated successfully";


                return RedirectToAction("Index");
            }

            return View(obj);

        }




        // DELETE 


        // Get

        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }

            // var CoverTypeFromDB = _db.Categories.Find(id);
            var CoverTypeFromDBFirst = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
            if (CoverTypeFromDBFirst == null)
            {
                return NotFound();
            }

            return View(CoverTypeFromDBFirst);
        }




        // Post
        // With the action name you can give DeletePost another name for in the delete view
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);

            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.CoverType.Remove(obj);

            _unitOfWork.Save();
            // Tempdata is a temporary message that will be in the view untill you refresh the page => look @ the _layout file (partial) how to implement them!
            TempData["success"] = "CoverType deleted successfully";


            return RedirectToAction("Index");
        }

    }
}

Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Linq;
using System.Collections.Generic;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        // making the connection true the dependency injection in the controller 
        private readonly IUnitOfWork _unitOfWork;

        private readonly IWebHostEnvironment _hostEnvironment;

        // making the constructor for the connection true the dependency injection in the controller

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }


        // READ
        public IActionResult Index()
        {
            // calling DB information table categories
            IEnumerable<Product> objProductList = _unitOfWork.Product.GetAll();
            return View(objProductList);
        }
      


            // UPDATE
        //GET
        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                 Product = new(),
                // this is how you can use projections with the .Select 
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                CoverTypeList = _unitOfWork.CoverType.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),

            };

          
            // Id has to exist or can not be 0
            if (id == null || id == 0)
            {
                // create product
                // ViewBag is to transfer something from controller to view and not vice-versa
                // ViewBag is ideal for temporary data that is not in a model
                // ViewBag's life only lasts during the current http request. The value will be null if redirection occurs.
                //ViewBag.CategoryList = CategoryList;
                // Using viewData instead of the ViewBag. They are both similar. With ViewData you have to assign a key and also CAST it in the view.
                // The key of ViewData and the property of ViewBag must not match because viewbag inserts data into viewdata dictionarry
                //ViewData["CoverTypeList"]= CoverTypeList;
                // You have also TempData => uses session to store the data.
                // TempData can be used to store only one time messages like error messages, validation messages...
                return View(productVM);
            }
            else
            {
                //Update product
            }
            return View(productVM);
        }


        //POST
        [HttpPost]

        [ValidateAntiForgeryToken]
        // IFormFile you need to be able to upload a file in the view
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {

          

            if (ModelState.IsValid)
            {
                // This is to get the roothpath 
                string wwwRootPath = _hostEnvironment.WebRootPath;
                // if the file is not null
                if (file != null)
                {
                    // This is to not use the existing name => this way it is renamed and uploaded
                    string fileName = Guid.NewGuid().ToString();
                    // this is where the images will be stored => you have to make a variable and then combine the path
                    var uploads = Path.Combine(wwwRootPath, @"images\products");
                    // The file will be renamed, but we want to keep the same extension
                    var extension = Path.GetExtension(file.FileName);

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create)) 
                    {
                        // This is copy the file to the fileStreams
                        file.CopyTo(fileStreams);
                    }
                    // This is what will be saved in the DB
                    obj.Product.ImagerUrl = @"\images\products" + fileName + extension;
                }
                // Based on the primary key the update wil automaticly update all of the properties
                //_unitOfWork.CoverType.Update(obj);

                _unitOfWork.Product.Add(obj.Product);
                _unitOfWork.Save();
                TempData["success"] = "Product created successfully";
                return RedirectToAction("Index");
            }

            return View(obj);

        }




        // DELETE 


        // Get

        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }

            // var CoverTypeFromDB = _db.Categories.Find(id);
            var CoverTypeFromDBFirst = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
            if (CoverTypeFromDBFirst == null)
            {
                return NotFound();
            }

            return View(CoverTypeFromDBFirst);
        }




        // Post
        // With the action name you can give DeletePost another name for in the delete view
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);

            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.CoverType.Remove(obj);

            _unitOfWork.Save();
            // Tempdata is a temporary message that will be in the view untill you refresh the page => look @ the _layout file (partial) how to implement them!
            TempData["success"] = "CoverType deleted successfully";


            return RedirectToAction("Index");
        }

    }
}

Controllers/CategoryController.cs
using BulkyBookWeb.Data;
using BulkyBookWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections;

namespace BulkyBookWeb.Controllers
{
    public class CategoryController : Controller
    {
        // making the connection true the dependency injection in the controller 
        private readonly ApplicationDbContext _db;

        // making the constructor for the connection true the dependency injection in the controller

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }


        // READ
        public IActionResult Index()
        {
            // calling DB information table categories
            IEnumerable<Category> objCategoryList = _db.Categories;
            return View(objCategoryList);
        }





        // POST

        //GET
        public IActionResult Create()
        {
            return View();
        }


        //POST
        [HttpPost]
        // This is needed so that they can't hack the website true the form
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            // custom validation => we want to make sure we do not add any category wich has the same name and display order
            // you need summary validation to display this without giving a key name of the form
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                // adding a custom error
                // If you want to add the orrer to the form and not to the summary validation => change key CustomError to Name or display order to display validation in form
                ModelState.AddModelError("CustomError", "The DisplayOrder cannot exactly match the Name.");
            }
            // Check validations serverside => modalstate.isvalid
            if (ModelState.IsValid)
            {
                // this is a command to add something to the DB
                _db.Categories.Add(obj);
                // adding saveChanges it wil go to the DB and save the changes
                _db.SaveChanges();
                TempData["success"] = "Category created successfully";
                // with redirectaction you can go back to the index instead of staying on the page
                // This will look for the index action inside the same controller
                // if you had to redirect to another controller, you can just do it like this example index HomeController ("index","HomeController")
                return RedirectToAction("Index");
            }
            // if you don't fill in nothing in create category, it will return the view.
            return View(obj);








            // UPDATE
        }
        //GET
        // Edit will display the existing functionality of the category that was selected.
        // Here we will retrieve an intiger that will be id
        public IActionResult Edit(int? id)
        {
            // Id has to exist or can not be 0
            if (id == null || id == 0)
            {
                return NotFound();
            }
            // Here we extract the id from de db with the find method. This way it tries to find the primary key based on the primary key of the table and assigned that to the variable categoryFromDB.
            var categoryFromDB = _db.Categories.Find(id);

            // 2 other ways to retrieve an ID from category

            // Here it will find the Id and it will return the first one it finds with the id you arsking for.
            // var categoryFromDBFirst = _db.Categories.FirstOrDefault(u=>u.Id==id);
            // it returns only one element but without throwing an exeption
            // var categoryFromDBSingle = _db.Categories.SingleOrDefault(u=>u.Id==id);

            // If it doesn't find a category it will display not found
            if (categoryFromDB == null)
            {
                return NotFound();
            }
            // If it founds the category it will return it to the view
            return View(categoryFromDB);
        }


        //POST
        [HttpPost]

        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {

            if (obj.Name == obj.DisplayOrder.ToString())
            {

                ModelState.AddModelError("CustomError", "The DisplayOrder cannot exactly match the Name.");
            }

            if (ModelState.IsValid)
            {
                // Based on the primary key the update wil automaticly update all of the properties
                _db.Categories.Update(obj);

                _db.SaveChanges();
                TempData["success"] = "Category updated successfully";


                return RedirectToAction("Index");
            }

            return View(obj);

        }




        // DELETE 


        // Get

        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }

            var categoryFromDB = _db.Categories.Find(id);

            if (categoryFromDB == null)
            {
                return NotFound();
            }

            return View(categoryFromDB);
        }




        // Post
        // With the action name you can give DeletePost another name for in the delete view
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Categories.Find(id);

            if (obj == null)
            {
                return NotFound();
            }
            _db.Categories.Remove(obj);

            _db.SaveChanges();
            // Tempdata is a temporary message that will be in the view untill you refresh the page => look @ the _layout file (partial) how to implement them!
            TempData["success"] = "Category deleted successfully";


            return RedirectToAction("Index");
        }

    } 
}

    

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home<span class="visually-hidden">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Managment</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                <div class="dropdown-divider"></div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
@*                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <!-- Addint the tempdata in the notification file  and added the partial view in the _layout so it's displayed wherever I want to -->
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-primary">
        <div class="container">
            &copy; 2022 - BulkyBookWeb
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
<!-- This is how you use tempdata, When it is not null, it will show the message given in the controller with the key (succes in this case) -->
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
}
@if(TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]');
    </script>
}